/** 研究端 · 回测实例表单：合约白名单（排序、一键填充、扫描器 universe 等） */
export const BACKTEST_INSTANCE_WHITELIST = Object.freeze([
  'SIRENUSDT', 'EDGEUSDT', 'STOUSDT', 'PIPPINUSDT', 'AIOTUSDT', 'CTSIUSDT', 'DUSDT', 'PUFFERUSDT', 'JCTUSDT', 'ARIAUSDT',
  'CUSDT', 'POLYXUSDT', 'RLSUSDT', 'PTBUSDT', 'THEUSDT', 'MASKUSDT', 'DEXEUSDT', 'BSBUSDT', 'LINEAUSDT', 'ESPORTSUSDT',
  'ZECUSDT', 'DUSKUSDT', 'PUMPUSDT', 'MUSDT', 'SIGNUSDT', 'JTOUSDT', 'BERAUSDT', 'ONGUSDT', 'CAKEUSDT', 'ZENUSDT',
  'SOLUSDT', 'RIVERUSDT', 'TAOUSDT', '1000PEPEUSDT', 'BARDUSDT', 'NOMUSDT', 'ALGOUSDT', 'XPLUSDT', 'ONTUSDT', 'FIDAUSDT',
  'SKYAIUSDT', 'NEARUSDT', 'NIGHTUSDT', 'ENAUSDT', 'BRUSDT', 'KERNELUSDT', 'FETUSDT', 'KITEUSDT', 'WLDUSDT', 'BEATUSDT',
  'HEMIUSDT', 'SAHARAUSDT', 'THETAUSDT', 'BASEDUSDT', 'DRIFTUSDT', 'ALTUSDT', 'SOLVUSDT', 'CFGUSDT', 'ASTERUSDT', 'CYSUSDT',
  'XMRUSDT', 'RENDERUSDT', 'WIFUSDT', 'ZKUSDT', 'SEIUSDT', 'FARTCOINUSDT', 'HIPPOUSDT', 'VETUSDT', 'LITUSDT', 'PAXGUSDT',
]);
