/**
 * 与后端 {@code com.example.crypto.config.TrendLiquidityWhitelist#SYMBOLS} 保持一致（Binance U 本位永续 jbar 品种名）。
 * 用于趋势扫描、成交量节拍/砖石构建、配对扫描器砖石模式、回测实例编辑下拉等。
 * 顺序：研究回测白名单（回测实例页「填充白名单」等）。
 */
export const TREND_LIQUIDITY_WHITELIST = [
  'SIRENUSDT', 'EDGEUSDT', 'STOUSDT', 'PIPPINUSDT', 'AIOTUSDT', 'CTSIUSDT', 'DUSDT', 'PUFFERUSDT', 'JCTUSDT', 'ARIAUSDT',
  'CUSDT', 'POLYXUSDT', 'RLSUSDT', 'PTBUSDT', 'THEUSDT', 'MASKUSDT', 'DEXEUSDT', 'BSBUSDT', 'LINEAUSDT', 'ESPORTSUSDT',
  'ZECUSDT', 'DUSKUSDT', 'PUMPUSDT', 'MUSDT', 'SIGNUSDT', 'JTOUSDT', 'BERAUSDT', 'ONGUSDT', 'CAKEUSDT', 'ZENUSDT',
  'SOLUSDT', 'RIVERUSDT', 'TAOUSDT', '1000PEPEUSDT', 'BARDUSDT', 'NOMUSDT', 'ALGOUSDT', 'XPLUSDT', 'ONTUSDT', 'FIDAUSDT',
  'SKYAIUSDT', 'NEARUSDT', 'NIGHTUSDT', 'ENAUSDT', 'BRUSDT', 'KERNELUSDT', 'FETUSDT', 'KITEUSDT', 'WLDUSDT', 'BEATUSDT',
  'HEMIUSDT', 'SAHARAUSDT', 'THETAUSDT', 'BASEDUSDT', 'DRIFTUSDT', 'ALTUSDT', 'SOLVUSDT', 'CFGUSDT', 'ASTERUSDT', 'CYSUSDT',
  'XMRUSDT', 'RENDERUSDT', 'WIFUSDT', 'ZKUSDT', 'SEIUSDT', 'FARTCOINUSDT', 'HIPPOUSDT', 'VETUSDT', 'LITUSDT', 'PAXGUSDT',
]

export const TREND_LIQUIDITY_WHITELIST_SET = new Set(TREND_LIQUIDITY_WHITELIST)
